### ISSUE TITLE
Handle null-bytes in session handler module

### ISSUE THREAD

**Issue by koleo** [aerospike/aerospike-client-php#100]
Session handler module embedded in _Aerospike PHP Extension_ can not store data containing null bytes strings (\0).

As null-bytes string is quite usual in PHP session values, that makes extension module unusable for most cases.

I am not a C programmer but maybe storing serialized data as a binary could solve this problem?

I mean Using `as_record_set_bytes` instead of `as_record_set_str`, and `as_record_get_bytes` instead of `as_record_get_str` in the following code:

https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike_session_handler.c#L363
https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike_session_handler.c#L300

Is it the right track?
Or someone has another idea how to solve this problem of null bytes?

For now, the workaround for storing sessions in Aerospike is to implement your own session handler, using Aerospike\Bytes class as described in [documentation](https://github.com/aerospike/aerospike-client-php/blob/master/doc/README.md#handling-unsupported-types) but it is unfortunate not to use the integrated session mode...

**Comment by bbulkow** [comment]
What character set are you using that allows null bytes in strings?

I think the actual issue is to detect the character set that PHP is running in, and convert from that character set to UTF-8 by default. Or to allow you to use your local character set then not be able to access the strings from other languages.

**Comment by sergeyklay** [comment]
In [Phalcon Incubator](https://github.com/phalcon/incubator/blob/2.1.x/Library/Phalcon/Session/Adapter/Aerospike.php#L133) we always use sort of wrapper to prepare data before writing / after reading

**Comment by koleo** [comment]
I noticed such null-bytes on some websites using Symfony Framework (SF 2.8). Charset is utf-8.

As you can read in the PdoSessionHandler section from Symfony documentation, we must expect some null-bytes in session data:

> Session data is a binary string that can contain non-printable characters like the null byte. For this reason it must be saved in a binary column in the database like BLOB in MySQL.


[http://api.symfony.com/2.8/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.html](http://api.symfony.com/2.8/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.html)

**Comment by xavierleune** [comment]
Hi,

Actually you can expect a null byte when you serialize an object which has a private property.

I just posted a [gist](https://gist.github.com/xavierleune/05cd60b366192abca6aba9d4ea10b439). You can reproduce the exact same output on PHP 5.6, compiling the aerospike extension with "--loglevel TRACE".

**Comment by xavierleune** [comment]
I pushed a Dockerfile, check out that: https://github.com/xavierleune/aerospike-client-php/pull/1/files
You'll easily reproduce the error :smile: 

Thanks

**Comment by xavierleune** [comment]
Hi everyone,
Did you had a chance to take a look on this issue ? Actually we are stuck with this :'(

**Comment by sergeyklay** [comment]
ping @rbotzer

**Comment by xavierleune** [comment]
Hi @bbulkow and @rbotzer.
Our teammate @aterrien just pushed the Pull Request #103 to address this issue. Can you please review it ?

Thanks!

**Comment by rbotzer** [comment]
Definitely will be. I'm heading to the office and going to talk to @jboone100 about it, though I'm sure he's seen the notification by now.

**Comment by koleo** [comment]
This has been merged in [v3.4.9]( https://github.com/aerospike/aerospike-client-php/releases/tag/3.4.9).
Closing the issue.
