### ISSUE TITLE
TTL seems to be not wrapped since PHP7

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-client-php#105]
A small test 
````php

<?php

$host = "192.168.56.80";

$config = array("hosts" => array(array("addr" => $host, "port" => 3000)));
$db = new Aerospike($config, false);

$key = $db->initKey('test', 'redis', 'myKey');

$db->put($key, array('r' => 10), 50);
$db->exists($key, $ret_val);

var_dump($ret_val);
````

The ttl received by exists call is always set to 1, should be greater.

**Comment by aminer** [comment]
Could you please share the environment data (OS and version, Aerospike Server version, php -v output)?

**Comment by bpaquet** [comment]
Server side :
aerospike 3.9.0.3 on linux ubuntu 14.04

Client side :
Mac OS X with php 7.1.0 beta2, latest version from git for aerospike client.

I can provide the full php -v later if needed.

**Comment by aminer** [comment]
So the reason why TTL is always set to 1, is because of the time difference between the server and the client. 

Here is a snippet from the Aerospike C Client:
```c
// Record may not have expired on server, but delay or clock differences may
// cause it to look expired on client. (We give the record to the app anyway
// to avoid internal cleanup complications.) Floor at 1, not 0, to avoid old
// "never expires" interpretation.
return server_void_time > now ? server_void_time - now : 1;
```

Full code: 
https://github.com/aerospike/aerospike-common/blob/d1d80414dc44b1eec85a484020adf4ec00f543ef/src/include/citrusleaf/cf_clock.h#L132

**Comment by bpaquet** [comment]
Thx, it's my problem.

Sorry about this wrong issue.

**Comment by aminer** [comment]
No worries! Please feel free to reach out at any time.
