### ISSUE TITLE
Segmantfault while initialization

### ISSUE THREAD

**Issue by bangbang93** [aerospike/aerospike-client-php#107]
php -r "new Aerospike(['hosts'=>[['addr'=>'10.9.12.205','port'=>3000]]]);"
[1]    76008 segmentation fault  php -r "new Aerospike(['hosts'=>[['addr'=>'10.9.12.205','port'=>3000]]]);"

Use aql can connect to server and do some query.But in php,got sigsegv both cli and php-fpm.

php -v
PHP 5.6.24 (cli) (built: Jul 22 2016 02:41:22) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

php -i |grep aerospike
Additional .ini files parsed => /usr/local/etc/php/5.6/conf.d/ext-aerospike.ini,
aerospike
aerospike support => enabled
aerospike version => 3.4.9
Registered save handlers => files user aerospike memcached redis 
async aerospike client => enabled

OSX 10.11.6

**Comment by bangbang93** [comment]
install with git clone && build.sh

make test failed in every case

**Comment by aminer** [comment]
Did you create a local configuration file for the tests, and configure the correct IP address for your server?

**Comment by bangbang93** [comment]
Well…no
But my php run into segment fault.And nodejs client works well.

**Comment by aminer** [comment]
OK, could you please configure the correct IP address for your server, then try to run the tests again:
cd src/aerospike/
cp tests/aerospike.local.skeleton tests/aerospike.local.inc
# change the IP in tests/aerospike.local.inc

**Comment by bangbang93** [comment]
OK,after configuration,some test was failed

=====================================================================
TIME END 2016-08-11 10:27:31

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   59
---------------------------------------------------------------------

Number of tests :  785               666
Tests skipped   :  119 ( 15.2%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    8 (  1.0%) (  1.2%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :  658 ( 83.8%) ( 98.8%)
---------------------------------------------------------------------
Time taken      :  708 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Aggregate - Aggregate float values [tests/phpt/Aggregate/normal_001.phpt]
query() on geoJSON data with predicate predicateGeoContainsGeoJSONPoint() [tests/phpt/Geospacial/testQueryGeoContainsGeoJSONPoint.phpt]
query() on geoJSON data with predicate predicateGeoContainsPoint() [tests/phpt/Geospacial/testQueryGeoContainsPoint.phpt]
GetNodes - Positive test [tests/phpt/GetNodes/TestGetNodesPositive.phpt]
Info - Positive for mcast [tests/phpt/Info/TestInfoPositiveForMcast.phpt]
Query - query call with incorrect ns and set [tests/phpt/Query/TestQueryWithIncorrectNSSet.phpt]
queryApply() with non-existent namespace and set [tests/phpt/QueryApply/error_001.phpt]
Tests if all the inserted records are removed by using digest. [tests/phpt/Remove/TestRemoveByDigest.phpt]
=====================================================================


> 在 2016年8月10日，下午11:23，Amine Rihane <notifications@github.com> 写道：
> 
> please

**Comment by bangbang93** [comment]
I use lldb load core dump file,got stack like this

```
➜  /cores lldb --core core.91776 
(lldb) target create --core "core.91776"
warning: (x86_64) /cores/core.91776 load command 165 LC_SEGMENT_64 has a fileoff + filesize (0x2d55a000) that extends beyond the end of the file (0x2d559000), the segment will be truncated to match
warning: (x86_64) /cores/core.91776 load command 166 LC_SEGMENT_64 has a fileoff (0x2d55a000) that extends beyond the end of the file (0x2d559000), ignoring this section
Core file '/cores/core.91776' (x86_64) was loaded.
(lldb) bt
* thread #1: tid = 0x0000, 0x00007fff989a3132 libsystem_c.dylib`strlen + 18, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff989a3132 libsystem_c.dylib`strlen + 18
    frame #1: 0x00007fff989fdb71 libsystem_c.dylib`strdup + 18
    frame #2: 0x000000010a999b38 swoole.so`seeds_init + 232
    frame #3: 0x000000010a999885 swoole.so`as_cluster_create + 197
    frame #4: 0x000000010a98fd92 swoole.so`aerospike_connect + 274
    frame #5: 0x000000010aa7bfd8 aerospike.so`zim_Aerospike___construct + 2280
    frame #6: 0x00000001098c33ad php`dtrace_execute_internal + 126
    frame #7: 0x000000010a905b9b xdebug.so`xdebug_execute_internal + 426
    frame #8: 0x000000010993dd2a php`zend_do_fcall_common_helper_SPEC + 1317
    frame #9: 0x00000001098f9f6a php`execute_ex + 973
    frame #10: 0x00000001098c32e9 php`dtrace_execute_ex + 226
    frame #11: 0x000000010a90587b xdebug.so`xdebug_execute_ex + 2352
    frame #12: 0x00000001098c568f php`zend_eval_stringl + 452
    frame #13: 0x00000001098c59b4 php`zend_eval_stringl_ex + 14
    frame #14: 0x000000010995f788 php`do_cli + 2816
    frame #15: 0x000000010995eb0e php`main + 1206
    frame #16: 0x00007fff8d1e65ad libdyld.dylib`start + 1
    frame #17: 0x00007fff8d1e65ad libdyld.dylib`start + 1
```
so i disable swoole.so in php.ini,aerospike client works well.No SIGSEGV.

This is my swoole version.
```
swoole

swoole support => enabled
Version => 1.8.5
YZ-Version => 1.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async mysql client => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
GCC AIO => enabled
pcre => enabled
zlib => enabled
async aerospike client => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_namespace => Off => Off
```
Maybe some change in swoole api?

**Comment by bangbang93** [comment]
I asked my teammate.He says our swoole has modify some function to support async aerospike.And Conflict with vanilla aerospike extension.
Sorry.

**Comment by aminer** [comment]
No problem, feel free to reach out to us at any time. 
Could you please tell me on which OS did you run the tests?

**Comment by bangbang93** [comment]
OSX 10.11.6
