### ISSUE TITLE
Segmentation fault while config have "shm" options

### ISSUE THREAD

**Issue by guoxiaod** [aerospike/aerospike-client-php#110]
in src/aerospike/aerospike_transform.c:2726
aerospike_transform_set_shm_in_config()
does not support php 7.0

just run :
php -r '$config = ["hosts" => [["addr"=>"127.0.0.1", "port"=>3000]], "shm"=>[]]; $client = new Aerospike($config, true);'

will Segmentation fault

Aerospike Client version: 3.4.9

**Comment by aminer** [comment]
Thanks for reporting this! The issue is fixed, and will be included in the next release.

**Comment by aminer** [comment]
Fixed in release 3.4.10.

**Comment by jboone100** [comment]
Can you try using the 3.4.11 version of the client released today?

**Comment by jboone100** [comment]
Closing this. Please re-open if you continue to see the issue.
