### ISSUE TITLE
Aggregate returning null in PHP 7

### ISSUE THREAD

**Issue by guilhermecoltro** [aerospike/aerospike-client-php#115]
I'm performing an aggregate query on Aerospike.
When it runs with AQL it works, but with PHP Client (Version 3.4.10), doesn't work.
The AQL command is:
`aggregate interval.sum("daily", "type", "print") on test.tracker where flight_id = 4`
Output:
`MAP('{1376438400:{"start":"2013-08-14 00:00:00", "value":129500, "final":"2013-08-14 23:59:59"}, 1377216000:{"start":"2013-08-23 00:00:00", "value":10667...`

and in PHP:
```
$config = [
	"hosts"     => array(
        ["addr" => "127.0.0.1", "port" => 3000],
    ),
    "options"   => array(
        \Aerospike::OPT_CONNECT_TIMEOUT => 15000,
        \Aerospike::OPT_READ_TIMEOUT    => 15000,
        \Aerospike::OPT_WRITE_TIMEOUT   => 15000,
    )
];

$db = new \Aerospike(["hosts" => $config['hosts']], true, $config['options']);
if(!$db->isConnected()){
   	echo "Aerospike not connected.";
   	exit();
}
$sts    = $db->register(ini_get('aerospike.udf.lua_user_path') . '/interval.lua', "interval.lua");
if ($sts != \Aerospike::OK) {
    $db->close();
    echo "Error to register UDF.";
    exit();
}

$namespace = "test";
$set = "tracker";
$where = \Aerospike::predicateEquals('flight_id', 4);
$module = 'interval';
$fn = 'sum';
$args = ['daily', 'type', 'print'];

$status = $this->client->aggregate($this->namespace, $set, $where, $module, $fn, $args, $output, $config['options']);

var_dump($status, $output);exit;
```

Output:
```
int(0) // That's the status
NULL // That's the value which should be returned
```

I also checked if it was running over all data, and it was, but, as i said, the value returned always was _null_ in PHP.

Could you check this, please?

**Comment by jboone100** [comment]
Please try using the 3.4.11 version of the client released today.

**Comment by guilhermecoltro** [comment]
It works perfectly!
Thx!!
(Closing this issue)
