### ISSUE TITLE
Aerospike.php final class

### ISSUE THREAD

**Issue by devrck** [aerospike/aerospike-client-php#128]
Why did you make the Aerospike.php a final class? Coud you please provide a valid reason?

**Comment by sergeyklay** [comment]
Performance?

**Comment by devrck** [comment]
Following the blog of ocramius the creator of [ProxyManager](https://github.com/Ocramius/ProxyManager)  in his post [When to declare classes final](http://ocramius.github.io/blog/when-to-declare-classes-final/):

> Final classes only work effectively under following assumptions:
> 
>  1. There is an abstraction (interface) that the final class implements
>  2. All of the public API of the final class is part of that interface

**Comment by sergeyklay** [comment]
3. They were created in the С language

_P.S. Ocramius do not use C_

**Comment by devrck** [comment]
@sergeyklay in C you can not do final classes from what I know only in C++ :smile: this is no excuse, also we are talking about a **php class** .

**Comment by jboone100** [comment]
@devrck: What is your use case? Mocking for testing?

**Comment by devrck** [comment]
@jboone100 I wanna extend \Aerospike php class to add some more functionalities. I did a wrapper around it (not my ideal solution) but I'm curious for the decision because according to best practices it should be just `public class Aerospike`  .

**Comment by sergeyklay** [comment]
@devrck I mean Zend Engine (C level)

**Comment by devrck** [comment]
@sergeyklay 

Yes your example is what I have now.
 
I know the term composition over inheritance but sometimes is not the only way to go because the Open/Closed principle says a class can be extendable.
Some new languages like `Go` don't have inheritance and they've said "inherit by composition" but still it's kind of the same thing.
Also I'm not saying that `final` classes are a bad thing. They have their purpose but in our use case I don't see why set it as `final class Aerospike` ( **This is my original question** ) because there is no interface or abstract class that specifies its functionalities.

**Comment by jboone100** [comment]
@rbotzer reminded me that we had already removed the final designator. Unfortunately, there was a wayward merge commit that added it back. It will be removed for the next release.

**Comment by sergeyklay** [comment]
Wow

**Comment by jboone100** [comment]
Final designator removed in 3.4.14 release.

**Comment by sergeyklay** [comment]
@jboone100 Could you please reopen the issue because class still final :)
