### ISSUE TITLE
Aerospike::ERR_BIN_TYPE is not defined

### ISSUE THREAD

**Issue by solidfoxrock** [aerospike/aerospike-client-php#13]
Hi, you have this constant in https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike.md but not in the code

**Comment by rbotzer** [comment]
Thanks for spotting that. We match the status codes the C-client exposes, but I guess that one got forgotten during a cleanup. I'll take it out.

**Comment by solidfoxrock** [comment]
Thanks :)

**Comment by rbotzer** [comment]
This has been updated in the master branch, and will be part of the next release.
