### ISSUE TITLE
error connections would be exceeded: 300

### ISSUE THREAD

**Issue by evalsocket** [aerospike/aerospike-client-php#130]
When i am trying to connect aerospike(PHP Client) then i am getting an error

> object(Aerospike)#4 (2) { ["errorno":"Aerospike":private]=>
> int(-7) ["error":"Aerospike":private]=> string(59) "Max node BB93615E8270008 connections would be exceeded: 300" }

**Comment by guoxiaod** [comment]
the default value of aerospike.max_threads is 300, try to increase it ?

$ php --re aerospike |grep -A2 aerospike.max_threads
    Entry [ aerospike.max_threads <ALL> ]
      Current = '300'
