### ISSUE TITLE
Can i save igbinary data in aerospike in PHP 

### ISSUE THREAD

**Issue by evalsocket** [aerospike/aerospike-client-php#135]
check [#166](https://github.com/aerospike/aerospike-server/issues/166#event-919523089) i open a issue in aerospike repository And @wchu-citrusleaf  closed that issue and told me that aerospike support  binary data. I am not able to save binary data in aerospike in php. Any Idea

$key = $aerospikeObj->createKey(AERO_DB_NAMESPACE,$aeroConfig,strtoupper($process_key));
$bins = ["data" => igbinary_serialize($document)];
$aerospikeObj->setKey($key,$bins,AERO_URC_EXPIRY_TIME);

**Comment by koleo** [comment]
See [Handling Unsupported Types](https://github.com/aerospike/aerospike-client-php/blob/master/doc/README.md#handling-unsupported-types) from the README file.



You should be able to use the provided [Bytes Class](https://github.com/aerospike/aerospike-client-php/blob/master/src/Bytes.php) like this:

```
$key = $aerospikeObj->createKey(AERO_DB_NAMESPACE,$aeroConfig,strtoupper($process_key));
$bDocument = new \Aerospike\Bytes($document);
$bins = ["data" => $bDocument];
$aerospikeObj->setKey($key,$bins,AERO_URC_EXPIRY_TIME);
```
