### ISSUE TITLE
Large Data Types functionality

### ISSUE THREAD

**Issue by daniel-adlantic** [aerospike/aerospike-client-php#18]
Many of the LDT functions are not yet implemented. Currently these are:
```php
LList::filter($module, $function, array $args, array &$elements, $min=null, $max=null)
LMap::filter($module, $function, array $args, array &$elements)
LSet::filter($module, $function, array $args, array &$elements)
LStack::pop(&$element)
LStack::scan(&$elements)
LStack::filter($module, $function, array $args, array &$elements)
```
Especially ```LStack::pop``` and ```LStack::scan``` is something we really miss.

Are there any plans to get these implemented?

**Comment by rbotzer** [comment]
Hello again, Daniel. We are currently re-evaluating all the LDT functionality and making consolidations.
The recommended data structure to use is Llist, which should support lstack usages. So, the API will be made simpler, more stable, and over time faster.  When those changes are in place I will modify the LDT library.  Till then I suggest you use LList and stay tuned. :+1:

**Comment by daniel-adlantic** [comment]
Hello Ronen,

Thanks for your reply. Fortunately we are still in a data modelling stage so we have a lot of room to move around. I was basically hoping to use LStack as a sort of queue structure to push updates to our data warehouse. This means there is going to be a lot of the same stuff in the LDT and that objects will live in Aerospike for a short period of time.

LList and LSet won't work for this purpose as they both only take unique objects. LMap seems to be OK with this, however this requires unique keys to be generated. I'd rather not do this as this takes some time.

Do you know of any other structures for data queuing?

**Comment by rbotzer** [comment]
Well, at the same time this LDT consolidation will take place the native complex types list and map are going to be enhanced with extra functionality, and those are much faster than LDTs.

What's the use case like? how big is the data you're pushing onto the stack, and how many objects would it have (more or less)?

We can also have this discussion by email or skype.

**Comment by daniel-adlantic** [comment]
The problem I have with native types is that the whole records needs to be re-written, which in my eyes is asking for consistency issues.

Case is that we are running a high impact ad-auction and we would like to collect data for later processing. These are details such as site id, geo id, browser id, view port resolution. Also I'd like to collect which campaigns took part in the auction, or didn't and for what reason they didn't (targeting, budget constraints etc.).

In terms of individual object size I'm currently looking at 2 options. One where I'll combine all this data into 1 object, another where this will be split into multiple smaller objects. Obviously in the second option there will be some overlap. In terms bytes, object size will largely vary depending on how many campaigns we have running. Stack/List size will be in the region of thousands to tens of thousands.

**Comment by rbotzer** [comment]
You would use the check-and-set pattern to avoid overwriting, if your business logic was sensitive to it. Basically, you get the record's generation using get() or exists() and set the put() with OPT_POLICY_GEN as POLICY_GEN_EQ of the current generation. In the case of a status ERR_RECORD_GENERATION you re-read and merge with the new generation (or execute some other logic that fits your case). This is a pattern current users have implemented, but we're aware that it's not ideal. Therefore, we are working on adding push/pop operations to list and set/get operations to map, avoiding the need for a full put(). This added functionality is coming soon.

LDTs will not be immediately deprecated, its just that there will be consolidation and large types outside of that will be left as-is. Some concepts of LDT will be moved into the native complex types over time. This is one of the current priorities.

You can have multiple records represent campaign data, with secondary indexes used to allow for queries as a means of gathering what you're looking for. One benefit of doing it this way is being able to attach a ttl to those records, so they clean themselves up, something you can't do with LDTs objects.

**Comment by rbotzer** [comment]
Just as a note, [this discussion](https://discuss.aerospike.com/t/lstack-remove-individual-element/848/5) and others about LDTs are on our forum https://discuss.aerospike.com

**Comment by daniel-adlantic** [comment]
Hello Ronen,

Thanks for the info. I'm not really a fan of the suggested method. Especially the if "if it fails, just try again part". I'll keep an eye on the push/pop developments. Until then I am most probably going to use a dedicated queuing library (ZMQ) for this part of the system.
