### ISSUE TITLE
Unable to set record to int (DateTime timestamp)

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-php#19]
Hello,

I've been trying to store a simple unix timestamp in a record but it fails with an "Unable to set record to int" error:
![Error](http://puu.sh/fA42z/905e940de8.png)

```
$now = new DateTime();
$bins = ['registrationDate' => $now->getTimestamp()];

$status = $this->db->put($key, $bins);

if($status != Aerospike::OK) {
	self::$lastError = 'Account registration error: ' . $this->db->error();
	return false;
}
```

Did I do something wrong here?
I deleted and recreated the key with modified data a few times before that.
If this error occurs when I change data types on a new write: How can I overwrite the data with the new data type?
Deleting and recreating doesn't seem to work.

**Comment by rbotzer** [comment]
Hello Eduard,

The problem isn't with the timestamp, it's with the length of the bin name. That has a limit of 14 characters, and 'registrationDate' is 16 characters long.

Pretty goofy, I admit, but that's a current limitation on the server side. So, come up with a clever shorter bin name, and I'm going to clarify this better in the documentation for the PHP client.

**Comment by blitzprog** [comment]
Oh I see, my bad. Thanks for the clarification!
