### ISSUE TITLE
Return type of the function processStatusCode for LDT's is string?

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#22]
The return type of the function `processStatusCode` in `LDT.php` is an string??

    $status = $mybin->add($event);
    
    echo gettype($status); // gives string
    echo gettype($mybin->errorno()); // gives string

This gives an error when comparing to class constants!!

If the value of `$status` is `1402`, it should match with `Aerospike\LDT\LDT::ERR_UNIQUE_KEY`, but,

```
    $status === Aerospike\LDT\LDT::ERR_UNIQUE_KEY
    $mybin->errorno() === Aerospike\LDT\LDT::ERR_UNIQUE_KEY
```

gives false? Is it intended behavior?

**Comment by rbotzer** [comment]
Fixed in release >= 3.3.10
