### ISSUE TITLE
Searching an LDT with a key other than the PK

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#23]
How can I search bins without the primary key.

Please refer to line 158 the example - https://github.com/aerospike/aerospike-client-php/blob/master/examples/ldt/llist.php#L158

It searches by "key". when i try to search by "clientid", it gives a `Error [1433] LDT-Key (Unique) Function Not Found` error.

I tried to create an index on `clientid` and search, but it didn't work as well. It throws the error given above.

I tried the following:

```
// create an index on clientid
$status = $db->createIndex("test", "vehicles", "clientid", Aerospike::INDEX_TYPE_INTEGER, "clientid_index");
if ($status == Aerospike::OK) {
    echo success();
} else {
    echo standard_fail($db);
}

// search by clientid
$status = $rental_history->find(array('clientid' => 100100123), $elements);
if ($status === Aerospike::OK) {
    echo success();
    var_dump($elements);
} else {
    echo standard_fail($rental_history);
}

// drop the index
$status = $db->dropIndex("test", "clientid_index");
if ($status == Aerospike::OK) {
   echo success();
} else {
   echo standard_fail($db);
}
```

Please let me know. Thanks

**Comment by pushpesh4u** [comment]
Hello,

Let me know if this is possible.

Thanks

**Comment by rbotzer** [comment]
Hi. Currently the llist search is done on a field 'key'. To change that you need to set your own filter function written in Lua. As you saw in the API this is not yet implemented. As we discussed before, I am going to review the changes to LDT an bring the PHP library up to date. In the meanwhile, if you need to search by clientid please duplicate its value into 'key' and the find() method will work.
