### ISSUE TITLE
unable to install client with the given steps.

### ISSUE THREAD

**Issue by Abhi11981198** [aerospike/aerospike-client-php#24]
$ make test  . All tests fail.

**Comment by Abhi11981198** [comment]
i m installing on ubuntu 14.04 . everything is configured but at last when running "$ make test " in src/aerospike . All tests fail.

**Comment by rbotzer** [comment]
Great. So it builds fine, then you `sudo make install`, then you configured your `php.ini`, right?

Do you have an aerospike server running locally before calling `make test`?

**Comment by Abhi11981198** [comment]
no, my server is on another machine, but i have tested also on a machine where aerospike server is locally installed. i have tried on both machines.

**Comment by rbotzer** [comment]
OK, you will need to define where your server is for the tests.

Create a file in your Aerospike client for PHP directory at `src/aerospike/test/aerospike.local.inc`. For example my two node cluster has the following:

```php
<?php
    define("AEROSPIKE_CONFIG_NAME", "192.168.119.3");
    define("AEROSPIKE_CONFIG_PORT", 3000);
    define("AEROSPIKE_CONFIG_NAME2", "192.168.119.3");
    define("AEROSPIKE_CONFIG_PORT2", 3010);
?>
```

Your configuration can have a single NAME/PORT pair, too.
Then

```bash
cd src/aerospike
./build.sh
# edit the php.ini as described at the end of the build
sudo make install
make test
```

Beyond the actual tests, which we run before releasing, and which run on Travis-CI, the main question I have is whether the module is installed for you, and whether you can run the example scripts.

**Comment by Abhi11981198** [comment]
all tests pass except :  
Put - PUT List on Wrong IP [tests/phpt/Put/CheckListWithWrongIP.phpt]
Reconnect - Check for Basic Reconnect after close for a non-persistent connection. [tests/phpt/Reconnect/TestReconnectNonPersistentConnectionPositive.phpt]
 

and here is my php snapshot...

<?php
$config = [
					"hosts" => [
							["addr" => "my server address", "port" => 3000]
					]
			];

            try {
                $db = new Aerospike($config);
            }catch (Exception $ex){
                echo $ex;
            }
?>


after running this script,  Fatal error: Class 'Aerospike' not found in /var/www/html/src/xyz.php .

**Comment by rbotzer** [comment]
OK, we're getting progress :+1: . Those tests are known problems and in progress.

Let's check if your module is installed:

`php -m | grep aerospike`

This should show that the aerospike extension installed for this PHP interpreter (the `sudo make install` step). Sometimes there are multiple PHP interpreters and the one it installed for isn't the one you're running the script with...

**Comment by Abhi11981198** [comment]
yes, it is showing aerospike.
and $ php -i | grep aerospike gives following : 
/etc/php5/cli/conf.d/aerospike.ini
aerospike
aerospike support => enabled
aerospike version => 3.0
Registered save handlers => files user aerospike
OLDPWD => /home/ubuntu/vendor/aerospike/aerospike-client-php/src/aerospike/tests
PWD => /home/ubuntu/vendor/aerospike/aerospike-client-php/src/aerospike
_SERVER["OLDPWD"] => /home/ubuntu/vendor/aerospike/aerospike-client-php/src/aerospike/tests
_SERVER["PWD"] => /home/ubuntu/vendor/aerospike/aerospike-client-php/src/aerospike



and how do i get to know whether i am running the correct interpretor.

**Comment by Abhi11981198** [comment]
phpinfo(); in the above script show PHP Version 5.5.9-1ubuntu4.6,
but not showing aerospike in the modules.

**Comment by rbotzer** [comment]
Okay, so at least we know the PHP interpreter on your PATH is working and loading the module.

`which php` should show its path.

If you run the following:
```
which php
php -m | grep aerospike
php -i | grep _SERVER | grep _ 
```

The info variable _SERVER["_"] shows the path of the executing script.

So one thing could be the case here - if your script is executing in a webserver context it will be calling a different interpreter. The command line one (CLI) has its own config file, and the one used by the webserver is different. For example if it's an Apache (Prefork MPM) with mod_php, or if it's Nginx using PHP-FPM. Please let me know how you're running that script.

Look inside /etc/php5 - there's cli in there, but also different subdirectories. Make sure the config block loading the aerospike module is in both versions. `ls /etc/php5` ?

**Comment by Abhi11981198** [comment]
thanks alot. it was apache with mod_php. i have changed the apache.ini with those 3 lines of directives. and now it is working. one more thing $db->get($key, $record, [ ], $option ).  Is $record is the desired result? If not then how can i get those records from the get call. 

once again thanks.

**Comment by rbotzer** [comment]
No problem. PHP configuration is still confusing at times, after doing this for 16 years.

Yes, that's one way to get it, though you don't need the third and fourth arguments unless you need to limit the bins you get back, or want to change some default behavior of the client.

Take a look at the [PHP documentation](http://www.aerospike.com/docs/client/php/) on the Aerospike site, specifically the [Quick Guide](http://www.aerospike.com/docs/client/php/usage/). Next, run some of the [examples](https://github.com/aerospike/aerospike-client-php/tree/master/examples). Finally, the GitHub repository includes the [API documentation](https://github.com/aerospike/aerospike-client-php/blob/master/doc/README.md).

Let me know if you feel like those need improvement. It's a work in progress and I appreciate the feedback.
