### ISSUE TITLE
get() function not working but exists() working on a record. 

### ISSUE THREAD

**Issue by Abhi11981198** [aerospike/aerospike-client-php#25]
hello, 
i have an existing set, "xyz" in namespace "test". $db->get($key, $record) gives null record. but $db->exists($key) works fine. i have tried to create a new set "demo"  and put some records. On the set demo $db->get($key, $record) works fine. why i can't get the records from "xyz" while i can get from "demo" ?
plz help.

**Comment by rbotzer** [comment]
Hi. When you say that exists works fine, what is your key, and what do you get if you var_dump() its metadata? Is it null?

I'd like to see something like the following, and the output from running it.
```php
<php
$db = new aerospike($config);
var_dump($db->isConnected());

$key = $db->initKey('test', 'xyx', ...
var_dump($key);
$status = $db->exists($key, $metadata);
var_dump($status, $metadata);

$status = $db->get($key, $record);
var_dump($status, $record);
?>

**Comment by Abhi11981198** [comment]
array(3) { ["ns"]=> string(3) "bar" ["set"]=> string(10) "publishers" ["key"]=> string(2) "56" }

int(0) array(2) { ["generation"]=> int(2) ["ttl"]=> int(4294967295) }

int(1) array(0) { }.


this is the output of above code. in last line status is 1 and record is missing,

**Comment by Abhi11981198** [comment]
i can get record from aql as well as java client.

**Comment by rbotzer** [comment]
Again, can you please quote the PHP code that matches the output? I assume you haven't changed the values and that a namespace 'bar' does exist.

**Comment by Abhi11981198** [comment]
$key = $db->initKey('bar', 'publishers', '56');
var_dump($key);
$status = $db->exists($key, $metadata);
var_dump($status, $metadata);

$status = $db->get($key, $record);
var_dump($status, $record);

**Comment by Abhi11981198** [comment]
$filter = Array("abc","xyz")
I have used filter as third argument in get(), now its working, 
now the problem is, without filter it returns 1 as status.

**Comment by Abhi11981198** [comment]
In every case without filter i am getting error but after adding filter i get result.

**Comment by Abhi11981198** [comment]
exactly i got the issue, in my set there are bin named "status" and "date". these two bins are creating problem. because of these i am unable to get records without filter. and after apllying filters if these two added then also status is non-zero. 

i have imported mysql database in aerospike, in mysql "status" column is of type boolean, and "date" column is of type datetime. now , what's the problem if these two bins are creating problem.

**Comment by rbotzer** [comment]
Yeah, I was going to ask you about the actual data in the row. Usually when any of the language clients runs into an 'unsupported' type (that is one that is not integer, string, bytes, list or map) it will usually serialize that data and store it in bytes. This method, however, does not work cross-language.

For example, if PHP sees a boolean it will serialize it and store it as a bytes with type AS_BYTES_PHP. (See: [Handling Unsupported Types](https://github.com/aerospike/aerospike-client-php/blob/master/doc/README.md)). That means a Java client would not know what to do with that field. I don't know how you imported your MySQL data (with which client or tool), but I assume it has stored the unsupported in some specific kind of _bytes_ and therefore it's generating an error.

For cross-language compatibility it's recommended to use your own common serializer across the languages. For PHP look at [setSerializer](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_setserializer.md) and [setDeserializer](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_setdeserializer.md).

**Comment by Abhi11981198** [comment]
i imported data using slick library and java client. plz suggest how to import data with java client and use that data with php client.

**Comment by rbotzer** [comment]
Let me get back to you on that. One option is to write an import script in PHP MySQL dump using a custom serializer and making sure your Java client uses the same serializer.

Please let me know if you intend to use the data across different (language) clients.

**Comment by Abhi11981198** [comment]
no, only one time import is needed via java client. rest of the transaction will be done with php client. if any other way to import data, plz suggest.

**Comment by rbotzer** [comment]
I suggest that you do the following:

* Create a PHP script that uses both MySQLi (or any other MySQL client) and aerospike modules.
* Execute a `SELECT * FROM table_name` and iterate through the results as an array using [mysqli_result::fetch_assoc()](http://php.net/manual/en/mysqli-result.fetch-assoc.php).
* Assemble the bins you want to insert from the fetched row. Skip any key-value pair coming from MySQL with a `NULL`.
* Insert into aerospike using put().
* This will ensure that your records only contain bins that have real values, and they'll be stored in a way that subsequents get() calls can use.
