### ISSUE TITLE
Key length in maps is limited to 14

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#28]
There is a 14 character limit in Aerospike for keys.

I am trying to import data from redis to aerospike. The key length in Redis in some cases, much longer than that.

Is there any way to handle that.

**Comment by rbotzer** [comment]
No, that's a current limitation for bin names (See: [FAQ](http://www.aerospike.com/docs/guide/FAQ.html). You'll have to come up with a renaming schema that works for you at the moment.  The issue has been [raised before](https://discuss.aerospike.com/t/bin-name-wondering-why-we-have-the-limitations-of-maximum-14-characters-of-any-single-byte-double-byte-characters-are-not-allowed-for-bin-names/514), so it's something we're aware of.

**Comment by pushpesh4u** [comment]
Ok. The bin name length is tied to 14 characters.

But, can we have key length greater in the LDT's.

**Comment by rbotzer** [comment]
There should not be any limit to map keys, not LDT, nor regular (complex type) maps.

That said, when I was verifying your question I ran into a bug with the PHP client.

```php
<?php
$config = ['hosts'=>[['addr'=>'192.168.119.3','port'=>3000]]];
$db = new Aerospike($config);
$bins = [ 'thisseemstobetoobigofakeyname' => 2 ];
$key = $db->initKey('test','demo','longkeyname_test');
$status = $db->put($key, $bins);
if ($status !== Aerospike::OK) {
    var_dump($status, $db->error());
}
$bins = [ 'thisalsoseemstobetoobigofakeyname' => 'the cake is a lie!' ];
$key = $db->initKey('test','demo','longkeyname_test');
$status = $db->put($key, $bins);
if ($status !== Aerospike::OK) {
    var_dump($status, $db->error());
    exit(1);
}
$status = $db->get($key, $record);
var_dump($record);
```

Gives the following output:

```
int(-1)
string(27) "Unable to set record to int"
int(-1)
string(32) "Unable to set record to a string"
```

**Comment by rbotzer** [comment]
Also, I've tested and there is no limit of 14 characters on the keys of an array which is being stored in an LDT. The bug exists only for PHP arrays which are being cast to an Aerospike map.

**Comment by rbotzer** [comment]
Oops, I tested it wrong. Actually there's no limits on the key length in a map type either.  So the 14 character limit only applies to the bin names.

For example, this works:
```php
$config = ['hosts'=>[['addr'=>'192.168.119.3','port'=>3000]]];
$db = new Aerospike($config);
$bins = [ 'my_bin'=> ['thisseemstobetoobigofakeyname' => 2 ]];
$key = $db->initKey('test','demo','longkeyname_test');
$status = $db->put($key, $bins);
if ($status !== Aerospike::OK) {
        var_dump($status, $db->error());
}
$bins = [ 'another_bin'=> ['thisalsoseemstobetoobigofakeyname' => 'the cake is a lie!' ]];
$key = $db->initKey('test','demo','longkeyname_test');
$status = $db->put($key, $bins);
if ($status !== Aerospike::OK) {
        var_dump($status, $db->error());
            exit(1);
}
$status = $db->get($key, $record);
var_dump($record);
```
