### ISSUE TITLE
Cache miss while benchmarking aerospike

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#31]
I am trying to benchmark get's from aerospike LList LDT vs Redis.

Here is the gist - https://gist.github.com/pushpesh4u/d6c475313dc4dd9c33e0

This is tested on a single server. There are about 2 million keys in the LList LDT.

I am using persistent connections.

Ubuntu 14.04, php 5.6.

The data that I am testing against exists in both caches, *right now, I am testing cache in RAM only*.

In jmeter, I have created two tests.

I created 50 threads and and 600 loops with a ramp-up period of 1 sec(concurrent). This will run the script 30K times.

In each loop, it makes a http connection to url where I am creating the redis/aerospike object and trying to search the given key and if the key exists, get the value.

It works without any issue in Redis.

I am seeing some issues with aerospike which are oulined below.

**Sometimes, the ldt object fails to instantiate.** By this, I mean the `isLDT` function fails.

![1](https://cloud.githubusercontent.com/assets/1575349/6436986/109bdc2e-c0de-11e4-9210-1f844b67ca4a.png)

**Sometimes, it fails to find the key in cache (cache miss).**

![2](https://cloud.githubusercontent.com/assets/1575349/6436987/109c0334-c0de-11e4-80cd-de6e94961ea6.png)

_Does it have anything to do with the **replication-factor 2** defined in the config file, whereas I am using only one machine as of now?_

Please let me know why is this happening in some cases (cache miss / instantiation failure). Am I doing something wrong? Redis does not give any issues.

Thanks,

**Comment by rbotzer** [comment]
Hey Pushpesh, thanks for all the testing you've been doing and the useful detailed bug reports. Can you move this to https://discuss.aerospike.com? It's probably more a general LDT question than particularly a PHP one, so that's a more common knowledge base.

**Comment by pushpesh4u** [comment]
ok, will do that.

**Comment by rbotzer** [comment]
Follows up on the discussion forum topic [Cache miss in benchmarking against Redis](https://discuss.aerospike.com/t/cache-miss-in-benchmarking-against-redis/999/)
