### ISSUE TITLE
System giving input/output error for a configuration

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#32]
I tried to put `load-at-start true` as per this doc

I changed the `storage-engine` to device.

http://www.slideshare.net/AerospikeDB/linked-in-twitter-facebook-google-email-embed-configuring-aerospike-part-2/51

When i restarted the server, it have the below error and after that it crashed.

What could be the reason here.

Deprecated parameter load-at-startup in cnf.c at line 73.

The system has become unresponsive

**Comment by rbotzer** [comment]
Hi Pushpesh, similarly, this should be moved to https://discuss.aerospike.com . There's an engineer assigned to each topic, so a DevOps one would know better how to answer your question.
