### ISSUE TITLE
Oracle solaris version

### ISSUE THREAD

**Issue by irbisoff** [aerospike/aerospike-client-php#36]
Do you have any plans to make php client library compatible to Oracle Solaris ? Currently it does not build without minor changes in code, but when built it randomly crashes php memory, leading to segaults.

**Comment by bbulkow** [comment]
We honestly get few requests for Solaris and PHP. We're happy to accept pull requests that solve any issues, or work together to fix any issues you find.

We're working pretty hard on PHP7 and HHVM, though !
