### ISSUE TITLE
Deprecated ldt's

### ISSUE THREAD

**Issue by pushpesh4u** [aerospike/aerospike-client-php#37]
Even though all LDT's except LList are deprecated now, their examples are still there to be seen.

https://github.com/aerospike/aerospike-client-php/tree/master/examples/ldt

Do they still work or the LList will suffice for them.

**Comment by rbotzer** [comment]
The other LDTs are still around, but you should not be writing new code with them, and should take the time before their removal to migrate to LList. In the meanwhile LList is being expanded and optimized.

Thanks for pointing out the examples are still there. I will remove them soon.
