### ISSUE TITLE
install failed on Ubuntu 10.04, php 5.3

### ISSUE THREAD

**Issue by gwijayas** [aerospike/aerospike-client-php#38]
I have old server Ubuntu 10.04, with php 5.3.27(build manually) in specific location.

I have installed aerospike-client-c with command `USE_LUAMOD=0 make` and check it's dependency:
```
$ ldd /usr/local/lib/libaerospike.so
	linux-vdso.so.1 =>  (0x00007fff607ff000)
	libm.so.6 => /lib/libm.so.6 (0x00007f88e8253000)
	libc.so.6 => /lib/libc.so.6 (0x00007f88e7ecc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f88e876a000)
```

And then copy all header files in directory under `include` to `/usr/local/include`, well except for `ck` because I failed on build php extension if header ck_* not directly under `/usr/local/include`

To build php extension, under directory `aerospike-client-php/src/aerospike/`, I run 

```
$ /opt/php/5.3/bin/phpize
$ ./configure --with-php-config=/opt/php/5.3/bin/php-config
$ make
$ make install
```
And load the extension in `php.ini`. But if I run `/opt/php/5.3/bin/php -m`, I get the following message:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php/5.3/lib/php/20090626/aerospike.so' - /opt/php/5.3/lib/php/20090626/aerospike.so: undefined symbol: g_as_log in Unknown on line 0
```

TIA

**Comment by gwijayas** [comment]
Just another test

* With Ubuntu 13.10, PHP 5.5.19(build manually), error message same with above. Build aerospike php using `build.sh`
```
$ ldd modules/aerospike.so 
	linux-vdso.so.1 =>  (0x00007fff9e3fe000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007ff71b4d1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff71b2c9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff71af00000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff71acfc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff71aae3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff71a8c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff71bbfa000)
$ php -dextension=modules/aerospike.so -a
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/apache22/php/5.5/lib/php/20121212/aerospike.so' - /opt/apache22/php/5.5/lib/php/20121212/aerospike.so: undefined symbol: g_as_log in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/opt/apache22/php/5.5/lib/php/20121212/aerospike.so' - /opt/apache22/php/5.5/lib/php/20121212/aerospike.so: undefined symbol: g_as_log in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/apache22/php/5.5/lib/php/20121212/aerospike.so' - /opt/apache22/php/5.5/lib/php/20121212/aerospike.so: undefined symbol: g_as_log in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/opt/apache22/php/5.5/lib/php/20121212/aerospike.so' - /opt/apache22/php/5.5/lib/php/20121212/aerospike.so: undefined symbol: g_as_log in Unknown on line 0
Interactive mode enabled

```
* With Ubuntu 14.04, PHP 5.5.20(build manually), success. No error message, build aerospike php with `build.sh`
```
$ php -dextension=modules/aerospike.so -a
Interactive mode enabled
```

**Comment by rbotzer** [comment]
Alright, we are going to have support for `./configure` options which will allow you to build without the `build.sh` script, but that's not ready yet. For now follow the [README.md](https://github.com/aerospike/aerospike-client-php/blob/master/README.md) for the build instructions.

We support LTS versions of Ubuntu, as stated in the README. 10.04 is too old, and the odd-numbered builds aren't LTS. Ubuntu doesn't support them either once an LTS is out.  Specifically to the version of 5.3, anything prior to 5.3.3 uses an older version of Zend Engine. I'll update the doc to make that clear.
