### ISSUE TITLE
Aerospike::query() does not return stored key value

### ISSUE THREAD

**Issue by trinhtran** [aerospike/aerospike-client-php#39]
I have these records stored in a set with option Aerospike::OPT_POLICY_KEY => Aerospike::POLICY_KEY_SEND.

set,key,source_id,name_last,name_first
test,12345,1,namel1,namef1
test,12346,5,namel2,namef2

When I use Aerospike::get() with the same option, I am able to get the key values back with the record.

But when I use Aerospike::query(), the key values are not returned with the records, key values are all NULL.  Should the keys be returned in the results since they are being stored?

**Comment by rbotzer** [comment]
Hi. Yes, if you stored a key with a record during a put() you should see that key value on the query() results. It's a bug otherwise. 

Can you give me the environment data, please? Which OS and version, the PHP version, the release of our client you're using.  Thanks.

**Comment by trinhtran** [comment]
Mac OSX Vagrant Box (http://www.aerospike.com/download/server)
PHP Client 3.3.1

Thanks!

**Comment by rbotzer** [comment]
Thanks for the details. I'll look into it, though it's likely that moving up to our latest release (>= 3.3.11) will get around the problem.

**Comment by trinhtran** [comment]
I just updated to 3.3.11, the key values are still NULL.

**Comment by rbotzer** [comment]
Alright, I'm testing on that same vagrant instance (Aerospike vagrant cloud instance for OS X, on VMWare), I installed PHP 5.5.23 and the PHP client release 3.3.12, and I don't see any problem.

```php
<?php
$config = ['hosts'=>[['addr'=>'127.0.0.1','port'=>3000]]];
$db = new Aerospike($config);

$status = $db->createIndex("test", "test", "subject", Aerospike::INDEX_TYPE_STRING, "test_subject_idx");
$key = $db->initKey('test','test','i_play_portal_2');
$db->remove($key);
$bins = [ 'subject' => 'Chell', 'i_did_not_die' => 'the cake is a lie!', 'dou_bl_e' => '::' ];
$status = $db->put($key, $bins, 99, [ Aerospike::OPT_POLICY_KEY => Aerospike::POLICY_KEY_SEND ]);
if ($status !== Aerospike::OK) {
    var_dump($status, $db->error());
    exit(1);
}
$status = $db->get($key, $record, null, [ Aerospike::OPT_POLICY_KEY => Aerospike::POLICY_KEY_SEND ]);
var_dump($record['key']);

var_dump("=========================================================");

$record = null;
$where = Aerospike::predicateEquals("subject", 'Chell');
$status = $db->query("test", "test", $where, function ($record) use (&$results) {
    var_dump($record['key']);
});

$db->close();

?>
```

I get the following

```
[vagrant@localhost vagrant]$ php test_39.php 
array(4) {
  ["ns"]=>
  string(4) "test"
  ["set"]=>
  string(4) "test"
  ["key"]=>
  string(15) "i_play_portal_2"
  ["digest"]=>
  string(20) "
              ?w?Rh?E???6?Ң
                           ?"
}
string(57) "========================================================="
array(4) {
  ["ns"]=>
  string(4) "test"
  ["set"]=>
  string(4) "test"
  ["key"]=>
  string(15) "i_play_portal_2"
  ["digest"]=>
  string(20) "
              ?w?Rh?E???6?Ң
                           ?"
}
```

Do you mind upgrading to 3.3.12 and checking that script? Let me know if you see different results from the ones I got. :cake:

**Comment by trinhtran** [comment]
Sorry, I haven't had a chance to get back to this yet.  I will try upgrade both the VM as well as the PHP client.  Thanks for looking into this.  I will follow up asap.

**Comment by trinhtran** [comment]
Ok this is working.  Thanks again.

**Comment by rbotzer** [comment]
Thanks for verifying!
