### ISSUE TITLE
bug operate incr php strong type

### ISSUE THREAD

**Issue by mahaidongs** [aerospike/aerospike-client-php#44]
$db->increment($key,'a','1');   yes 
but  
$operations = array( 
  array("op" => Aerospike::OPERATOR_INCR, "bin" => "a", "val" =>"1") 
); 
$status = $db->operate($key, $operations, $returned);      is wrong  

only can use: 
$operations = array( 
  array("op" => Aerospike::OPERATOR_INCR, "bin" => "a", "val" =>1) 
);

**Comment by mahaidongs** [comment]
php is not strong type   "1" eq 1, so when i put   bin  a string number such as "1" on  exist bin name "a","a" is a string,   when i use incr will error;    what  can i to ?  if($db->errorno() == 12){
 $db->get($Key,$a);
$db->put($Key,array('a'=> intval($a['a']+ $inc)));
}  ?

**Comment by rbotzer** [comment]
Hey, thanks for finding that bug. It's not really a misunderstanding of the nature of PHP :stuck_out_tongue_winking_eye:

**Comment by mahaidongs** [comment]
i think you can refer   redis  incr    ,when it is string number  , you can change it type to number; thanks, i like aerospike ,but i think it hard use.

**Comment by rbotzer** [comment]
I can see the convenience of type casting a numeric string for you, but it's pretty common and simple to use `(int) $val` or `intval($val)` in PHP code. PHP 7 is coming soon with scalar type hinting, so get ready. This will become standard.

**Comment by rbotzer** [comment]
This should be fixed with [release 3.3.16](https://github.com/aerospike/aerospike-client-php/releases/tag/3.3.16). Please verify.
