### ISSUE TITLE
HHVM version?

### ISSUE THREAD

**Issue by julienmarie** [aerospike/aerospike-client-php#5]
Hello, any chance to see a HHVM compatible version? It's too bad not to use a high performance database such as Aerospike and not being able to use HHVM with it.

**Comment by no1youknowz** [comment]
I'd like to see an HHVM version as well.

I attempted to compile this, but I don't know enough about cmake.

I did do a install on PHP and took the corresponding install files and placed them on an HHVM server.

I'm getting:
     Uncaught exception: Could not open extension /usr/lib64/hhvm/extensions/aerospike.so:   
     /usr/lib64/hhvm/extensions/aerospike.so: undefined symbol: executor_globals

Which sucks, as I wanted to use this.

**Comment by no1youknowz** [comment]
So i have spent today trying to get this to compile under hhvm.

I made a new cmake:

    HHVM_COMPAT_EXTENSION(aerospike, aerospike.c aerospike_policy.c aerospike_transform.c aerospike_helper.c aerospike_record_operations.c aerospike_udf.c aerospike_scan.c aerospike_query.c aerospike_index_operations.c aerospike_info_operations.c aerospike_batch_operations.c)

    HHVM_ADD_INCLUDES(aerospike "/root/aerospike-client-php/src/aerospike/../aerospike-client-c/include")
    HHVM_ADD_INCLUDES(aerospike "/root/aerospike-client-php/src/aerospike/../aerospike-client-c/include/ck")
    HHVM_ADD_INCLUDES(aerospike "/root/aerospike-client-php/src/aerospike/include")
    HHVM_ADD_INCLUDES(aerospike "/root/aerospike-client-php/src/aerospike/main")
    HHVM_ADD_INCLUDES(aerospike "/root/aerospike-client-php/src/aerospike")
    HHVM_ADD_INCLUDES(aerospike "/usr/include/hphp -I/usr/include/hphp/runtime/ext_hhvm")
    HHVM_ADD_INCLUDES(aerospike "/usr/include/hphp/runtime/ext_zend_compat/php-src/main")
    HHVM_ADD_INCLUDES(aerospike "/usr/include/hphp/runtime/ext_zend_compat/php-src/TSRM")
    HHVM_ADD_INCLUDES(aerospike "/usr/include/hphp/runtime/ext_zend_compat/php-src/Zend")

installed folly: https://github.com/facebook/folly/

Not to mention, I had to copy over directories such as aerospike-client-c, build, include, modules as hphpize does not make them.  I had to have a php build on standby to steal from.

It just doesn't compile.  Too many issues to mention.

Total waste of time. 

Don't expect anyone outside of aerospike to do this.  Too many things dependent on Zend/PHP that just wont be there in HHVM.

**Comment by rbotzer** [comment]
I appreciate the effort. Allegedly HHVM is compatible with a subset of that API, but apparently promises and reality diverge.  We will get around to trying to fix the compatibility issues that will allow the Zend extension to work with HHVM.  Afterward or alternatively we will implement a native client.

**Comment by no1youknowz** [comment]
Thanks for the update.  A native client doesnt really interest me right now.  Just getting it to work with HHVM should be a top priority.  You'll get more users then.

I've yet to move my codebase to hacklang, there is really no outstanding reason.  Unless hacklang starts to get some serious optimisations and this along generates say 20% more.  I may then be interested in that.

**Comment by bbulkow** [comment]
Product guy here. I will make a stronger statement than "we will get around to it" --- we are scheduling HHVM compatibility with a fairly high priority for the next few sprints. We find that agile PHP users start hitting the growth curve and need to swap in higher performance quickly - Aerospike's a great path for that. When they're doing that, they often want to swap in faster PHP implementations and various other toolchain bits - like HHVM.

If you're available for a quick chat, I'd love to hear what your perspective is. You can send me a private message through github, or look up my email on linkedin, and we can start a conversation.

**Comment by skynet** [comment]
Product guy: maybe you can also fix session handler with the php extension. :8ball:

**Comment by rbotzer** [comment]
@skynet code's open before you. Have at it.

**Comment by skynet** [comment]
Product guy seems to take more serious the $$$ you got in funding :))

**Comment by bbulkow** [comment]
@skynet Steady progress has been made for #11 --- including a release we hoped solved your problem but apparently didn't yet --- and we've been following up with you there. We're prioritizing that fix above the HHVM work, which makes @no1youknowz rather sad but session management is just more important.

**Comment by no1youknowz** [comment]
Hey @bbulkow lol no worries.  Functionality for HHVM will be released when its ready no doubt.  There have been a few occasions where I could have used it for my project but all in due time I guess.  Waiting patiently for it. :+1:

**Comment by skynet** [comment]
Thanks! I was so excited jumping from Redis to Aerospike, and ended up wasting a lot of time on a trivial PHP session handler. Good luck.

**Comment by no1youknowz** [comment]
Is there any concrete time-schedule you guys tentatively have?

I keep on running into specific issues that aerospike would solve.

Something better than just "get around to it" or  "next few sprints".  Is it possible for a "we'll try to hit this date?"

Many thanks! :+1:

**Comment by no1youknowz** [comment]
Just to let you guys knows, 3.6.0 is around the corner.

They have added async to mysql and memcached.

http://hhvm.com/blog/8405/coming-soon-in-hhvm

Hopefully you guys add async to aerospike :+1:

**Comment by rbotzer** [comment]
Yeah, I follow the blog and the twitter of some of the developers. We intend to support a similar style for HHVM eventually, implemented in Hack. First we'll try to get the C extension to compile against HHVM as it is right now.

**Comment by skynet** [comment]
Meanwhile, let's fix #11

**Comment by rbotzer** [comment]
Hey, since we're turning GitHub into Twitter, we just discussed it today :laughing:

**Comment by skynet** [comment]
:+1:  I can ping you on Twitter, as well. :)

**Comment by rbotzer** [comment]
@skynet check out Issue #11 please. @no1youknowz we're evaluating the changes needed for HHVM, unfortunately at first pass they don't seem trivial. I'll add more information in a few days.

**Comment by no1youknowz** [comment]
@rbotzer awesome.  thanks for starting to look at this.  Looking forward to more information. :+1:

**Comment by no1youknowz** [comment]
So 3.6 will be release weds.  Can't wait for async for mysql.  

Will aerospike have async capability?  Or will it require native hhvm version?

**Comment by rbotzer** [comment]
We are starting on a HNI based HHVM extension. The prototype will be pretty sparse, but if it works well we should be able to add the missing features on a bi-weekly release schedule.

**Comment by no1youknowz** [comment]
HNI being a Hack Native Interface?

So what were the negatives in implementing an HHVM C++ based extension, effectively wrapping a wrapper around the existing C++ library?  Thus having all the features instantly.

For example:  https://github.com/no1youknowz/zmq-extension-for-hhvm/tree/master/zmq

Which is an HHVM extension which wraps around the actual C++ library.

**Comment by rbotzer** [comment]
Hey Paul,

I may be having a problem with terminology here - still early with the HHVM migration and I need to catch up to an exciting new world of terms. We are going to write it in C++ so that Hack and PHP can interface with it. I believe that's what HNI _is_, but I may be wrong. Either way, we are talking about a C++ wrapper to our C client. We do not intend to write an extension in Hack itself - it's too slow compared to the C++ extension option, for one.

The things to tackle first are connection, and very simple key-value operations. One pain point that made it impossible to use the PHP extension with HHVM is that the Zend Engine constructs for persistence are not supported, so there goes storing the C client in the process for multiple requests. There are other unsupported APIs but that was a big one.

I hope that clarifies things. Either way, the prototype will confirm whether this approach is the right one, and if it is we'll build on it.

**Comment by no1youknowz** [comment]
Hey,

Thanks for the clarification.  The reason why I brought up Hack, is that the redis client that ships with HHVM is actually built in hack.

Good to know this is being written in C++.  I can't wait till its finally out :1.

Keep this issue updated.

Thanks

**Comment by no1youknowz** [comment]
Hey,

So any progress?  

Thanks

**Comment by cergfix** [comment]
Hello :) any news on this?

**Comment by rbotzer** [comment]
An alpha test is in progress with some core functionality. If all goes well we will release it soon and continue incrementally toward the full API.

**Comment by rbotzer** [comment]
Alright, folks, [release 0.2 of the HHVM client](https://github.com/aerospike/aerospike-client-hhvm/releases/tag/0.2) is out. We are on our way, and will end up implementing the same API as the PHP client (before considering possible HHVM-only async additions to it).

**Comment by no1youknowz** [comment]
Thanks @rbotzer much appreciated!

**Comment by bbulkow** [comment]
HHVM release 0.3 is out now too. Any comments?

**Comment by skynet** [comment]
:+1:
