### ISSUE TITLE
Configuration 'inheritance' model seems to be wrong

### ISSUE THREAD

**Issue by cpats007** [aerospike/aerospike-client-php#53]
Currently, the inheritance model should be as follows:

default values < config file values < constructor values < call value

When i define a time out in the php.ini of 10000 and then define a new timeout value in my constructor of anything greater (or less) than this value, the value is ignored, resulting in the .ini timeout being used (10000).

This has been tested and can be recreated.

**Comment by rbotzer** [comment]
This is issue AER-4344 internally.

**Comment by rbotzer** [comment]
This will be part of release 3.4.3.

**Comment by rbotzer** [comment]
Fixed in release 3.4.3.
