### ISSUE TITLE
Compatibility with PHP7

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-client-php#55]
The last released version does not build with PHP 7 RC3.

Is a new version for the driver planned for the PHP 7 final version ?

PHP7 is planned for november (https://wiki.php.net/todo/php70#timetable)

**Comment by rbotzer** [comment]
If you look at the code you'll see it's compatible with Zend Engine >= 5.3.3 and <= 5.6
We do plan to be compatible with PHP7, and hopefully in time for the 7.0.0 release.

**Comment by bpaquet** [comment]
Great news, thx.

**Comment by sergeyklay** [comment]
> Zend Engine >= 5.3.3 and <= 5.6

Do you mean Zend Engine 2

**Comment by rbotzer** [comment]
You got it. ZE3 is so different that trying to fit both ZE2 and ZE3 compatibility in the same extension is not spaghetti code, it's a pasta factory.

**Comment by sergeyklay** [comment]
:smile: :+1:

**Comment by bpaquet** [comment]
Hi @rbotzer ,

I'm not able to compile 3.4.7 against php7, and you closed the issue.

Am I wrong ? :)

Regards,

**Comment by dkinon** [comment]
ya, why was this closed?  php7 for aerospike client is the only thing standing between us and using aerospike.

**Comment by jboone100** [comment]
This is a duplicate of [#68](https://github.com/aerospike/aerospike-client-php/issues/68), but I'll reopen this until we release the PHP7 compatible code.

**Comment by bbulkow** [comment]
Prefer updvotes and watches on #68 . Notice that's been updated to state we are working on it although we don't have a committed release date.

My personal benchmarks of PHP7 are pretty exciting. I'm looking forward to the release.

**Comment by bpaquet** [comment]
Thx !
