### ISSUE TITLE
misspelling in build scripts: redhatenterpriceserver6

### ISSUE THREAD

**Issue by npenteado** [aerospike/aerospike-client-php#57]
line 54 of src/aerospike/scripts/aerospike-client-c.sh has a misspelling:  s/redhatenterpriceserver6/redhatenterpriseserver6/g

this will cause installs on RH enterprise 6 machines to fail

**Comment by rbotzer** [comment]
Thanks!  :+1:

**Comment by rbotzer** [comment]
Fixed in release 3.4.3.
