### ISSUE TITLE
Operate and TTL

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-client-php#63]
I have a problem with the operate command
- create a record with a TTL
- call operate on it (read a bin, and increment the same bin)
- TTL on the record is now infinite

I do not know if the problem is in PHP or in Aerospike.

**Comment by rbotzer** [comment]
Hi Bertrand. Are you using the `Aerospike::OPT_TTL` option to set the TTL of the [operate()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_operate.md)? This was added in [release 3.4.3](https://github.com/aerospike/aerospike-client-php/releases/tag/3.4.3).

Please let me know the OS, PHP version and client version on your client-size, and the version of your Aerospike server. Also, please attach a code snippet that reproduces the problem on your end. Thanks!

**Comment by bpaquet** [comment]
Here is a test code.

It failed under Mac and Linux, 3.4.2 and 3.4.5, PHP 5.5 or 5.6.

````php
<?php

$host = "192.168.56.80";

echo "Using Aerospike on " . $host . "\n";
$config = array("hosts" => array(array("addr" => $host, "port" => 3000)));
$db = new Aerospike($config, false);

$key = $db->initKey('test', 'toto', 'myKey');

$status = $db->put($key, array('titi' => 'aaaa'), 2);
assert($status == Aerospike::OK);

$status = $db->exists($key, $ret_val);
assert($status == Aerospike::OK);

assert($ret_val["ttl"] < 10);

$operations = array(
  array("op" => Aerospike::OPERATOR_INCR, "bin" => "x", "val" => 1),
  array("op" => Aerospike::OPERATOR_READ, "bin" => "x"),
);

$status = $db->operate($key, $operations, $ret_val);
assert($status == Aerospike::OK);

$status = $db->exists($key, $ret_val);
assert($status == Aerospike::OK);

assert($ret_val["ttl"] < 10);

**Comment by rbotzer** [comment]
Please use `Aerospike::OPT_TTL` to set the TTL for the record in the options of the [operate()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_operate.md) method. See the example given in the method. I have cleaned up the documentation as part of release 3.4.6.
