### ISSUE TITLE
Aerospike::PRIV_READ_WRITE

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#64]
Hello!

 I don't quite understand the `Aerospike::PRIV_READ_WRITE`
https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike_policy.h#L117
Can you please explain a bit more?

Thanks

**Comment by rbotzer** [comment]
The Enterprise Edition includes the 'security' feature, which includes roles and privileges. The ability to read and write data is one privilege that may be assigned to a role. Users (with username and password) have roles assigned, from which they inherit privileges.

The ability to read and write data is one of those privileges. Again, it does not apply to the community edition.

**Comment by sergeyklay** [comment]
Okay. Thanks
