### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#65]
Hello @rbotzer

I have written a letter to you.
I hope that this letter will not get to Spam folder because of quite a number of links in it.

If you saw the letter from me you can close this issue :)

Thanks

**Comment by rbotzer** [comment]
Hey, I found it. I'll get to it in a bit, Sergey.

**Comment by sergeyklay** [comment]
Well. I'm closing this because actually this is not a issue
