### ISSUE TITLE
Support CDT

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-client-php#66]
Hi,

Do you know when CDT will be supported by the PHP client ?
http://www.aerospike.com/docs/guide/cdt-list.html

Regards

**Comment by rbotzer** [comment]
Shortly after the C client does.

**Comment by rbotzer** [comment]
This will be part of release 3.4.7.

**Comment by rbotzer** [comment]
Standalone list operations methods are documented with the [Key-Value Methods](https://github.com/aerospike/aerospike-client-php/blob/master/doc/apiref_kv.md), and list operators have been added to [operate()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_operate.md#parameters) in 3.4.7.
