### ISSUE TITLE
Incorrect install documentation

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#69]
```sh
$ composer run-script post-install-cmd
...
Libraries have been installed in:
   /home/klay/tmp/vendor/aerospike/aerospike-client-php/src/aerospike/modules
...
Build complete.
Don't forget to run 'make test'.

cp: cannot create regular file ‘/usr/local/aerospike/lua/aerospike.lua’: Permission denied
cp: cannot create regular file ‘/usr/local/aerospike/lua/as.lua’: Permission denied
cp: cannot create regular file ‘/usr/local/aerospike/lua/stream_ops.lua’: Permission denied
```

**Comment by rbotzer** [comment]
I've removed the `sudo` part that used to be there in the past because it would halt the script if you didn't have the password. I am fine with a clear error that lets you know what you need to do. In this case you need to fix the permissions on that path, then run the install again.

**Comment by sergeyklay** [comment]
>  if you didn't have the password

> In this case you need to fix the permissions on that path
