### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#72]
Hello.
Documentation says:
>    // Status values returned by jobInfo()
>    const STATUS_UNDEF;      // the job's status is undefined.
>    const STATUS_INPROGRESS; // the job is currently running.
>    const STATUS_COMPLETED;  // the job completed successfully.

Ok. Lets try:
```php
<?php
$ext = new ReflectionExtension('Aerospike');

var_dump($ext->getVersion());
var_dump(Aerospike::STATUS_UNDEF);
```

```
string(5) "3.4.6"

Fatal error: Undefined class constant 'STATUS_UNDEF' in /tmp/test.php on line 4
```

```php
<?php
$ext = new ReflectionExtension('Aerospike');

var_dump($ext->getVersion());
var_dump(Aerospike::STATUS_INPROGRESS);
```

```
string(5) "3.4.6"

Fatal error: Undefined class constant 'STATUS_INPROGRESS' in /tmp/test.php on line 4
```

```php
<?php
$ext = new ReflectionExtension('Aerospike');

var_dump($ext->getVersion());
var_dump(Aerospike::STATUS_COMPLETED);
```

```
string(5) "3.4.6"

Fatal error: Undefined class constant 'STATUS_COMPLETED' in /tmp/test.php on line 4
```

Also the documentation says nothing about:
+ [JOB_QUERY](https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike_policy.c#L96)
+ [JOB_SCAN](https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike_policy.c#L97)

Also 

>  public int scanInfo ( integer $scan_id, array &$info [, array $options ] ) // DEPRECATED. use jobInfo()

Where is `jobInfo` method is documented?

Can you please explain this?
Thanks

**Comment by rbotzer** [comment]
Good catch on the constants. The method [jobInfo()](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_jobinfo.md) is in the doc and linked to from [UDF Methods](https://github.com/aerospike/aerospike-client-php/blob/master/doc/apiref_udf.md) section.

**Comment by rbotzer** [comment]
Fixed in master.

**Comment by sergeyklay** [comment]
:+1:
