### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#73]
Can you please provide the changelog in each release?

+ What is deprecated
+ What is fixed
+ What is introduced
+ What is removed
+ etc...

thanks

**Comment by rbotzer** [comment]
You mean a formal Changelog file? It would just be a duplicate of the [Releases](https://github.com/aerospike/aerospike-client-php/releases) section in the repo.

**Comment by sergeyklay** [comment]
Yah. I mean something like that https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md
But current release information not correspond to the actual changes. Actually more changes than in the release information

**Comment by rbotzer** [comment]
Yep, I'm committing that now. Thanks for the suggestion. :+1:
