### ISSUE TITLE
SERIALIZER_JSON

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#74]
You [have removed](https://github.com/aerospike/aerospike-client-php/commit/9ec7ecfb3acdd4d40bf8589e8d2cbc699e477d8b#diff-ad865a338012d9b4b02ebaf9b765046aL49) `SERIALIZER_JSON` from https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike.md

But constant [still present](https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike_policy.h#L93)

**Comment by rbotzer** [comment]
Gotcha. Constant is going :skull:
