### ISSUE TITLE
Use session.gc_maxlifetime for TTL instead of session.cache_expire 

### ISSUE THREAD

**Issue by jcross-class** [aerospike/aerospike-client-php#79]
The aerospike PHP Session handler is set up to use the session.cache_expire ini value for the aerospike record TTL:
[PHP ini session.cache_expire accessed](https://github.com/aerospike/aerospike-client-php/blob/9ec7ecfb3acdd4d40bf8589e8d2cbc699e477d8b/src/aerospike/aerospike_common.h#L102)
[PHP ini session.cache_expire used to set aerospike record TTL](https://github.com/aerospike/aerospike-client-php/blob/9ec7ecfb3acdd4d40bf8589e8d2cbc699e477d8b/src/aerospike/aerospike_session_handler.c#L351)

From reading through the PHP documentation on how sessions are handled, and from looking at how this is handled by other PHP session handlers, I think that instead of session.cache_expire for the aerospike record TTL, [session.gc_maxlifetime](http://php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime) should be used.  I've found this to be the case for other session handler implementations:
* For session information stored in files (the PHP default) session.gc_maxlifetime value is used to determine the earliest a file can be deleted from the file system.  The PHP documentation doesn't make that clear from what I can tell, but how it works is reference frequently when people discuss problems with PHP sessions.  [This is one such example](http://stackoverflow.com/a/3555570).
* The phpredis extension [uses session.gc_maxlifetime](https://github.com/phpredis/phpredis#php-session-handler)
* The php-memcached extension [uses session.gc_maxlifetime](https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached_session.c#L360)

The PHP documentation isn't clear, but [session.cache_expire](http://php.net/manual/en/session.configuration.php#ini.session.cache-expire) is used to set the HTTP expires header for any pages generated that use a PHP session.  The expires header tells the browser how long to use the returned page from cache.

[session.cache-limiter](http://php.net/manual/en/session.configuration.php#ini.session.cache-limiter) controls the caching mode for returned pages.  There's a decent explanation related to it [here](http://php.net/manual/en/function.session-cache-limiter.php).  By default, PHP sets session.cache-limiter to nocache.  When that is the case, the [documentation says that session.cache_expire](http://php.net/manual/en/session.configuration.php#ini.session.cache-expire) has no effect.  If someone switches from the default nocache to a caching mode, and then sets the session.cache_expire to a higher than default value (default is 180) to make the aerospike TTL a reasonable value (say 1 day), then that could cause client browsers to cache PHP session generated pages for too long.

**Comment by jboone100** [comment]
I had a look into this and you are correct. Version 3.4.8 of the PHP client will use `session.gc_maxlifetime` for the session timeout. Thanks for pointing this out.
