### ISSUE TITLE
3.4.7 CHANGELOG

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#81]
Hello

Could you please update CHANGELOG for 3.4.7 and create release note?

**Comment by rbotzer** [comment]
There's a bunch of docs and release notes associated, so I haven't announced this yet. Should be posted in the next day or so.

**Comment by rbotzer** [comment]
It's up, and the tag has been moved up to the latest commit. See the release notes for [3.4.7](https://github.com/aerospike/aerospike-client-php/releases/tag/3.4.7)
