### ISSUE TITLE
Documentation related to the constant is inconsistent with the codebase

### ISSUE THREAD

**Issue by sergeyklay** [aerospike/aerospike-client-php#83]
Hello
Current [aerospike.md](https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike.md) claims that there is a `OP_LIST_MERGE` constant;

Nevertheless:
```sh
$ php -a
Interactive mode enabled

php > var_dump(Aerospike::OP_LIST_MERGE);
PHP Fatal error:  Undefined class constant 'OP_LIST_MERGE' in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0

Fatal error: Undefined class constant 'OP_LIST_MERGE' in php shell code on line 1

Call Stack:
   23.9651     219240   1. {main}() php shell code:0
```

The next question I'm interested in:

The values of these constants have changed in a minor version

| Constant        | v3.4.6           | v3.4.7  |
| ------------- |:-------------:| -----:|
| OPT_POLICY_KEY | 11 | 12 |
| OPT_POLICY_GEN | 12 | 13 |
| OPT_POLICY_REPLICA | 13 | 14 |
| OPT_POLICY_CONSISTENCY | 14 | 15 |
| OPT_POLICY_COMMIT_LEVEL | 15 | 16 |
| OPT_TTL | 16 | 17 |
| USE_BATCH_DIRECT | 17 | 18 |

it seems to me that for changes which BC breaks should use the next major version, for example v3.5.0 (or if you guys follow Semver v4.0.0). Could you please explain a bit more your release process?

And finally:

The 3.4.7 version introduces `COMPRESSION_THRESHOLD` and `OP_GEOWITHINREGION` constants. Also, if I'm not mistaken the 3.4.6 version introduces `JOB_QUERY` and `JOB_SCAN` constants.

Can you please document them?

**Comment by sergeyklay** [comment]
@rbotzer, @jboone100 ping :)

**Comment by sergeyklay** [comment]
The 3.4.8 version [which is incorrectly called](https://github.com/aerospike/aerospike-client-php/issues/84) 3.4.7 introduces:

* `ERR_GEO_INVALID_GEOJSON`
* `INDEX_GEO2DSPHERE`
* `OP_GEOCONTAINSPOINT`

constants. Can you please document them?

**Comment by sergeyklay** [comment]
@rbotzer ping

**Comment by jboone100** [comment]
Thanks for pointing these out. OP_LIST_MERGE has been removed from the documentation since it is invalid. All others have been added to the documentation for the 3.4.9 release.
