### ISSUE TITLE
Error: Undefined class constant 'Aerospike::PRIV_WRITE'

### ISSUE THREAD

**Issue by devckonem** [aerospike/aerospike-client-php#90]
Hello,

The current constant is not defined in Aerospike, or not exposed.

**Comment by sergeyklay** [comment]
Same as #72

**Comment by devckonem** [comment]
Your right, closing here.

**Comment by sergeyklay** [comment]
@devckonem No no :) I mean that this issue is the result of sloppy programming and similar errors have already been :) But this issue not identical with #72

**Comment by jboone100** [comment]
Thanks for catching this. It is a documentation error. The actual constant is
`Aerospike:PRIV_READ_WRITE`

The documentation has been updated for the 3.4.9 release.
