### ISSUE TITLE
Aerospike::changePassword vs Aerospike::setPassword

### ISSUE THREAD

**Issue by devrck** [aerospike/aerospike-client-php#91]
Hello,

What is the difference between them?

P.S.: There is no documentation for Aerospike::setPassword.

**Comment by sergeyklay** [comment]
@devckonem https://github.com/aerospike/aerospike-client-php/blob/5288bbb479663d5f951096106f0318e8d0916315/src/aerospike/aerospike.c#L5416-L5424
