### ISSUE TITLE
Documentation: Session Handler TTL update

### ISSUE THREAD

**Issue by koleo** [aerospike/aerospike-client-php#94]
Since v3.4.8, ttl for session handler uses session.gc_maxlifetime instead of session.cache_expire.

Documentation should be updated:

https://github.com/aerospike/aerospike-client-php/blob/master/doc/aerospike_sessions.md

> ~~The value of session.cache_expire is used as the record ttl.~~
> The value of session.gc_maxlifetime is used as the record ttl.

**Comment by jboone100** [comment]
Thanks for catching that. Documentation will be updated in 3.4.9.
