### ISSUE TITLE
shm does not seem to work

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [aerospike/aerospike-client-php#96]
my configs are as following:
```
aerospike.shm.use=1
aerospike.shm.key=0xA5000001
aerospike.shm.max_nodes=16
aerospike.shm.max_namespaces=8
aerospike.shm.takeover_threshold_sec=30
```

I cannot seem to figure out why the shm is not showing up, a run of 
```
ipcs -m | grep 0xA5000001
```

returns nothing.

Below is what php reports
```
php -i | grep aerospike

aerospike
aerospike support => enabled
aerospike version => 3.4.7
Registered save handlers => files user aerospike redis rediscluster redis rediscluster 
```

**Comment by rbotzer** [comment]
Are you checking ipcs as your script is running? Also, unless you have more than 16 nodes you should only really need to enable shm. The rest are default values.

**Comment by Ewan-GrandSlam** [comment]
Yes I check while the scripts are running, the settings were just there really for example for someone else and I just happened to paste them.

**Comment by Ewan-GrandSlam** [comment]
I have managed to get it to work in a server environment, however not in a local (ubuntu) setup. I will close this out and say it is something conflicting on the local setup.
