### ISSUE TITLE
Examples with multiple hosts?

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [aerospike/aerospike-client-php#98]
I have been doing some testing and was wondering how to handle the following:

* 2 servers
* Split connections between all clustered servers

The scenario I ran had two servers, I configured both servers in the hosts array however only ever ended up making connections to the first member of the array. I then shut that first member down in hopes that we would then switch the servers we were requesting however then the requests just stopped being sent.

Is there a behaviour I am missing?

**Comment by rbotzer** [comment]
This is more of a question for the [discussion forum](http://discuss.aerospike.com), but the short version is that it takes some time before (a) the cluster notices that the node is down. That takes [timeout](http://www.aerospike.com/docs/reference/configuration#timeout) * [interval](http://www.aerospike.com/docs/reference/configuration#interval) milliseconds. (b) The client notices that the cluster has changed, which takes at most one cluster tending interval (by default 1s). 

Until that point the client may try to connect to a non-existent node, and time out. Your application should consider what to do with the timeout. It can skip on the operation. It can pause for the expected amount of time (server lag on knowing the node is down plus the client lag, by default 2.5s), then retry. It can put the operation on a deferred work queue. This is application knowledge. 

The node-down situation is one to be aware of. The opposite, a node joining the cluster, should be handled automatically until the client becomes aware, through proxy operations. If the client goes to the wrong node, the operation will be executed by that node on behalf of the client. No app-side code is required.
